name: Build and Deploy Credit Spread Jobs

on:
  push:
    branches:
      - master   # or your target branch
  workflow_dispatch:

env:
  NIFTY_CS_IMAGE_NAME: nifty-credit-spread:${{ github.run_number }}   # Change as needed
  NIFTY_CS_SIGNAL_IMAGE_NAME: nifty-credit-spread-signal:${{ github.run_number }}   # Change as needed
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.NIFTY_CS_IMAGE_NAME }} ./spread
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.NIFTY_CS_SIGNAL_IMAGE_NAME }} ./signal
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.NIFTY_CS_IMAGE_NAME }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.NIFTY_CS_SIGNAL_IMAGE_NAME }}

      - name: Deploy to Nifty Credit Spread Job
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp job update \
              --name ${{ secrets.CREDIT_SPREAD_JOB_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.NIFTY_CS_IMAGE_NAME }}

      - name: Deploy to Nifty Credit Spread Signal Job
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp job update \
              --name ${{ secrets.CREDIT_SPREAD_SIGNAL_JOB_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.NIFTY_CS_SIGNAL_IMAGE_NAME }}

      - name: Restart running Nifty Credit Spread Signal Job
        uses: azure/CLI@v1
        with:
          inlineScript: |
            running_jobs=$(az containerapp job execution list --name ${{ secrets.NIFTY_CS_SIGNAL_IMAGE_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "[?properties.status=='Running']")
            if [ "$running_jobs" != "[]" ]; then
              az containerapp job stop -n ${{ secrets.CREDIT_SPREAD_SIGNAL_JOB_NAME }} -g ${{ secrets.RESOURCE_GROUP }}
              az containerapp job start -n ${{ secrets.CREDIT_SPREAD_SIGNAL_JOB_NAME }} -g ${{ secrets.RESOURCE_GROUP }}
            fi

      - name: Restart running Nifty Credit Spread Job
        uses: azure/CLI@v1
        with:
          inlineScript: |
            running_jobs=$(az containerapp job execution list --name ${{ secrets.CREDIT_SPREAD_JOB_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "[?properties.status=='Running']")
            if [ "$running_jobs" != "[]" ]; then
              az containerapp job stop -n ${{ secrets.CREDIT_SPREAD_JOB_NAME }} -g ${{ secrets.RESOURCE_GROUP }}
              az containerapp job start -n ${{ secrets.CREDIT_SPREAD_JOB_NAME }} -g ${{ secrets.RESOURCE_GROUP }}
            fi
